export const GET_ALL_CARS= 'GET_ALL_CARS';
export const ALL_CARS_ERROR = 'ALL_CARS_ERROR'


export const GET_ALL_CATEGORIES= 'GET_ALL_CATEGORIES';
export const ALL_CATEGORIES_ERROR = 'ALL_CATEGORIES_ERROR'




